Fix lint
wechaty/wechaty-puppet-lark pull request #5
Opened 2021-02-09 11:41 UTC by Roxanne718

#4

2021-02-09 12:01 UTC, huan requested changes
Your fixes look great.

Please follow my reviews and change the logging messages to align to our standard message format, and then we will be able to merge it and move on.

Thank you very much!

2021-02-09 12:01 UTC, huan commented on src/puppet-lark.ts
> +    console.info(contactId)
change to:

```ts
log.verbose('PuppetLark', 'contactRawPayload(%s)', contactId)
```

2021-02-10 08:16 UTC, Roxanne718 commented
> Your fixes look great.
> 
> Please follow my reviews and change the logging messages to align to our standard message format, and then we will be able to merge it and move on.
> 
> Thank you very much!

I've modified the code, please check it again. Thanks！

2021-02-10 09:33 UTC, huan approved these changes
LGTM

2021-02-10 09:33 UTC, merged

2021-02-10 09:35 UTC, huan commented
This is a huge PR and it fixed most of the problems from the code base earlier.

Now all linting have been passed and it's ready for us to move forward.

Thank you @Roxanne718 for your effort to improve the quality of our code base, appreciate it!